### PR TITLE
 RTAPE server

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Server for the Chaosnet RTAPE remote tape protocol.  The drive name is used as a SIMH tape image file name.

### CODE REVIEW

**Comment by ams** [comment]
I agree with @eswenson1  ... it is already sorta bad with usim where cbridge and "Chaosnet for Unix" is required.

**Comment by eswenson1** [comment]
Yes, but supdup runs without cbridge.  It supports TCP/IP connections without any help from cbridge.  RTAPE is invoked by cbridge.

**Comment by ams** [comment]
SUPDUP is also more historical, it always lived in another place.

**Comment by larsbrinkhoff** [comment]
Looks like I closed this by mistake.  I'll see if I can reopen.

I will put several small Chaosnet programs in this repository.  I don't want to put all Chaosnet-related program in the chaosnet-bridge repository.

**Pull request closed without merging**
